version: '3.8'

volumes:
  dbdata:

services: 

  mongo: 
    image: mongo:latest
    restart: always
    volumes: 
      - dbdata:/data/db
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: appDb